version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /var/lib/pgadmin/data:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  redis:
    container_name: redis
    image: redis:6.2.4-alpine
    restart: on-failure
    ports:
      - 6379:6379

networks:
  postgres:
    driver: bridge
