### Create a new user
POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "123test",
    "name": "Cihat",
    "surname": "Yeşildağ",
    "address": "xyz mh. abc sk. No:56 Osmangazi/Bursa",
    "phoneNumber": "+905354330771",
    "type" : "patient"
}

### Sign in as an existing user
POST http://localhost:5000/users/signin
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "123test",
    "type": "patient"
}
