#######  DIAGNOSES



### Add new diagnose
POST http://localhost:5000/diagnoses
Content-Type: application/json

{
    "name": "cancer"
}

### Get all diagnoses
GET http://localhost:5000/diagnoses


### Get diagnose by id
GET http://localhost:5000/diagnoses/1

### Delete diagnose by id
DELETE http://localhost:5000/diagnoses/3

### Add new patient diagnose
POST http://localhost:5000/users/1/patient-diagnoses
Content-Type: application/json

{
    "diagnoseId": 1,
    "startDate": "2015-05-05"
}

### Get all diagnoses of a patient
GET http://localhost:5000/users/1/patient-diagnoses


### Approve a patient diagnose
PUT http://localhost:5000/users/1/patient-diagnoses/2/approval-status
Content-Type: application/json

{}


### Remove approval of a patient diagnose
DELETE http://localhost:5000/users/1/patient-diagnoses/2/approval-status
Content-Type: application/json

{}


######## MEDICATIONS

### Add new medication
POST http://localhost:5000/medications
Content-Type: application/json

{
    "name": "painkiller"
}

### Get all medications
GET http://localhost:5000/medications


### Get medication by id
GET http://localhost:5000/medications/1

### Delete medication by id
DELETE http://localhost:5000/medications/1

### Add new patient diagnose
POST http://localhost:5000/users/1/patient-medications
Content-Type: application/json

{
    "medicationId": 1
}

### Get all diagnoses of a patient
GET http://localhost:5000/users/1/patient-medications


####### RELATIVES

### Add a new relative for the patient
POST http://localhost:5000/users/1/relatives
Content-Type: application/json

{
    "name": "Yusuf Mert",
    "surname": "Toros",
    "phoneNumber": "+905355353535",
    "relation" : "friend"
}

### Get all relatives for the target patient
GET http://localhost:5000/users/1/relatives
Content-Type: application/json

### Get specified relative for the target patient
GET http://localhost:5000/users/1/relatives/1
Content-Type: application/json