version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /var/lib/pgadmin/data:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  redis:
    container_name: redis
    image: redis:6.2.4-alpine
    restart: on-failure
    ports:
      - 6379:6379

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTIC_PASSWORD=admin
      - ELASTICSEARCH_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=admin
      - ELASTIC_PASSWORD=admin
    depends_on:
      - es01
    links:
      - es01
    networks:
      - elastic

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge
